#!/bin/bash

set -euo pipefail

echo "Setting up development environment..."

DEV_ENV_HOME=~/Code/hasiburdev/dev-env

echo "Making scripts executable..."

chmod -R +x $DEV_ENV_HOME/bin
chmod -R +x $DEV_ENV_HOME/install

chmod +x ./install-all

echo "Dev environment setup completed successfully!"
